title: inherentlygia_photography
url: https://inherentlygia.work/
baseurl: 

author: Gia Lang
description: in the world, off the grid.

include: ['_pages']

collections_dir: series

collections:
  home:
    output: true
  sicily:
    output: true
  tokyo:
    output: true
  kyrgyzstan:
    output: true
  kazakhstan:
    output: true
  turkey:
    output: true

markdown: kramdown
kramdown:
  input: GFM
